= Psychic Villian Moves

== Hey now, you're an all star
When you *Put up your mental walls* roll \+Mundane.
On a hit, you can ignore one mental probing this scene.
On a 10+, you can ignore up to 2.
On a miss, you can  choose to take a condition to act as if you rolled a 7.

---

== Smile, Jessica
When you *leave yourself psychically vulnerable* roll \+Superior.
On a miss, the mental suggestion gets through to you and you lose control of yourself.
The GM dictates your next move.
On a 7-9, choose 2.
On a 10+ Choose 1.

* You struggle through it. Mark a condition.
* The suggestion influences your image of self. The GM shifts your labels.
* Psychic feedback. The GM asks you a question and you must answer truthfully.
The Character is now aware of the answer.

If you choose to allow the probing through, you may use it to come to know something about yourself or the aggressor.

In exchange for choosing an _additional option_ from the previous list (you may choose the same option twice), select one from the following list.
Even on a miss.

* Self-revelation. Shift your own labels
* Your emotions flood the empath. Choose a condition for the aggressor.
* Bypassing mental blocks. Ask one question of the aggressor that must be answered honestly.
