= Null: The Power Nullification Villain

Deep within AEGIS's Tranquil Gardens Prison facilities sits a perfectly normal cell.
Unlike the Ultimax Security prison's other cells, it lacks any sort of random-movement laser grid, alien-metal construction, or other type of _personalized escape prevention system_.
Or at least that's what it looks like.
In truth, the perfectly mundane walls made out of reinforced concrete and the perfectly adequate steel bars are designed to hold one of Halcyon's city's dreaded Super Villains.
One who can stand toe to toe against the city's most powerful super heroes.
Because to *Null*, they _aren't super at all_.

No one is quite sure of Null's Origin Story.
There are theories of course, but he refuses to confirm or deny them.
The leading theory is that he comes from a universe where super powers just don't exist, and that he has somehow brought that aspect of reality with him into this one.
Regardless, Null is an unusual villain to deal with. AEGIS's Magna-cuffs, designed to restrain the likes of Vanquish and The Strong Force cannot hold him.
Yet he is powerless against zip-ties.
Ray-guns and plasma rifles fizzle against him, and yet he will dive for cover when faced with 9mm rounds.
A super-powered punch that tears steel will knock the wind out of him, but his own punches will bruise impenetrable flesh.

Null is powerless, yes.
But to him, so is everyone else.

== Known information

Real Name:: John Doe

Super Name:: Null

Appearance:: Man in early to mid 30s, athletic build, cold hard eyes.

Super Appearance:: Military grade Tactical

Powers and Abilities::
* Skilled hand to hand combatant
* Weapons expertise
* Immunity to Super Powers.
** See Villain Move

== Villain Move: Null Pointer Exception
Null is immune or highly resistant to most known super powers, including the products of super or alien tech. Psychic scrying or supertech detection devices will not recognize him. Super Punches will hit him only as hard as a mundane punch. He can still be hit indirectly, such as by throwing things at him, or causing things to happen around him, but if the effect is obviously super in nature, such as a wall of ice or plasma bolts, he might ignore those too.

When *use your Super Powers* to make a move, you must roll with +Mundane if it is lower.
If you are using mundane skills acquired through hard-work, training, or natural ability, you may instead roll +Mundane if it is higher.
