= The Shifter
Erik Seguinte; S.M. Ketcham
v0.1, 2018-04-26

== Look

* Nondescript appearance, forgettable appearance, embarrassingly flashy apperance
* Androgynous gender, a-gender, stereotypical gender over-performance
* Ambiguous racial background, mid-toned skin, multiracial
* Easily-recognizable costume, no costume, monochrome costume
* Full hood, full mask, face paint/makeup, no mask

=== Tell

* Single lock of differently colored hair
* Unique and/or striking eyes
* Revealing coloration
* Fixed vocal range or tone
* Unable to transform clothing/uniform
* Identifying mark/tattoo
Discernible odor/perfume/pheromone


== Powers and abilities
You are mercurial. With a single tell that is only known to those who are extraordinarily observant, or personally familiarity to you, you are able to completely metamorphose. Your physical body, your mind, your talents, or all three can be altered by this shifting.

Decide how and when these changes manifest for you. Pick one form of personal alteration. (Including, but not limited to: animal transmutation, inanimate object reproduction, personality emulation, eidetic mimicry, skinwalking, etc.). Then pick one tell that bridges every form you adopt.

== ❑ Mercurial Nature
You can change. Adapt. Alter.
You can mold yourself to what your team needs for each new challenge.
But all that changing doesn’t leave much space to know who you really are.
Every new form comes at the cost of your sense of self, and you’ve begun to wonder if anything about you is actually locked.

Whenever you make any roll + a label, shift that label up and another down, as if you were accepting Influence.


== Shifter Moves
=== ❑ I'm as surprised as you are
When someone with Influence over you tells you who you are and *you reject their influence by firmly declaring who you see yourself to be*, take +2 to the roll.
On a hit, you much choose to clear a condition or mark potential by immediately acting to prove their view of you wrong. On a 10+ you may choose to do both with the same dramatic declaration of self.

=== ❑ Can you hear me now?
When you *pierce the mask by embodying someone your target respects, admires, or fears*, even on a miss you may ask 1 of the below questions. On a 10+, ask 2. Shift Danger down.

* What is your price in this situation?
* What is a dealbreaker for you in this situation?
* What about this situation makes you insecure?
* What would you rather be doing right now?
* What would it take in this situation to make you angry?
* How could you disrupt this situation, if you wanted to?
