= The Shifter
Erik Seguinte; S.M. Ketcham
v0.1, 2018-04-26

== Powers and abilities
You are mercurial. With a single tell that is only know to those who are extraordinarily observant, or personally familarial to you, you are able to completely metamorphose. Your physical body, your mind, your talents, or all three can be altered by this shifting.

Decide how and when these changes manifest for you. Pick one form of personal alteration. (Including, but not limited to: animal transmutation, inanimate object reproduction, personality emulation, eidetic mimicry, skinwalking, etc.). Then pick one tell that bridges every form you adopt.

== Mercurial Nature
You can change. Adapt. Alter.
You can mold yourself to what your team needs for each new challenge.
But all that changing doesn’t leave much space to know who you really are.
Every new form comes at the cost of your sense of self, and you’ve begun to wonder if anything about you is actually locked.

Whenever you make any roll + a label, shift that label up and another down, as if you were accepting Influence.
